# Generated by Django 6.0.4 on 2026-05-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='images',
            new_name='imagem',
        ),
    ]
