# Generated by Django 6.0.4 on 2026-05-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_images_banner_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
